# Configuration for merging weapon detection datasets
# This file defines how to combine multiple YOLO datasets into a unified multi-class dataset

# Unified class names (these will be the final classes in the merged dataset)
unified_classes:
  - "pistol"      # class_id: 0
  - "rifle"       # class_id: 1  
  - "knife"       # class_id: 2
  - "no_weapon"   # class_id: 3

# Dataset sources and their class mappings
datasets:
  # Pistol dataset
  - name: "pistol"
    path: "dataset/Pistols.v1-resize-416x416.yolov8"
    description: "Pistol detection dataset"
    class_mapping:
      0: 0  # pistol -> pistol (class_id 0)
  
  # Rifle dataset (has multiple rifle-related classes)  
  - name: "rifle"
    path: "dataset/rifle-detection.v1i.yolov8"
    description: "Rifle and long gun detection dataset"
    class_mapping:
      0: 1  # Rifle -> rifle (class_id 1)
      1: 0  # handgun -> pistol (class_id 0) 
      2: 1  # larga -> rifle (class_id 1)
      3: 1  # long gun -> rifle (class_id 1)
      4: 1  # rifle -> rifle (class_id 1)
  
  # Knife dataset
  - name: "knife" 
    path: "dataset/Knife Object Detection.v1i.yolov8"
    description: "Knife detection dataset"
    class_mapping:
      0: 2  # knife -> knife (class_id 2)
  
  # No weapon dataset (COCO negatives)
  - name: "no_weapon"
    path: "dataset/no_weapon_coco" 
    description: "No weapon / safe scenarios dataset"
    class_mapping: {}  # Empty labels, will be treated as no_weapon (class_id 3)

# Merge settings
merge_settings:
  train_ratio: 0.8
  val_ratio: 0.1  
  test_ratio: 0.1
  
# Class descriptions for documentation
class_descriptions:
  pistol: "Handguns, pistols, and similar compact firearms"
  rifle: "Rifles, long guns, and similar long-barreled firearms" 
  knife: "Knives, blades, and similar cutting weapons"
  no_weapon: "Normal scenes without visible weapons"